### ISSUE TITLE
Análisar CodeClimate e criar Issues a partir de problemas encontrados

### ISSUE THREAD

**Issue by vital-edu** [RadarMES20162/radar#2]
**Dupla:** Attany e Eduardo
1. Olhar o [CodeClimate](https://codeclimate.com/github/radar-parlamentar/radar) do Radar(Oficial)
2. Pesquisar por trechos de códigos que contenham possíveis problemas
3. Analisar esses trechos de código e verificar se representam um real problema
4. Criar issues no repositório da equipe a partir da análise do passo anterior
5. Identificar quais issues são possíveis de serem solucionadas
6. Atualizar o backlog da equipe com as issues passíveis de resolução
7. Escolher 1 das issues para ser concluída ainda nessa sprint e documentar na [Wiki de Planejamento](https://github.com/RadarMES20162/radar/wiki/Planejamento/)

**Comment by Attany** [comment]
As issues criadas foram as issues #6 e #7.
