### ISSUE TITLE
Documentar o processo de verificação do estilo do código com o Flake8

### ISSUE THREAD

**Issue by Attany** [RadarMES20162/radar#4]
O Flake8 possui o Pep8, uma ferramenta que verifica se o estilo do código respeita o padrão adotado pela comunidade Python. O processo para utilização do Flake8 precisa ser documentado.

**Comment by diraol** [comment]
O Flake8 verifica "só" o PEP8, mas existem outros padrões como Pylint, PEP257, PEP20.

Se quiserem, podem dar uma olhada na classe "linter" desse arquivo:
https://github.com/diraol/python-openflow/blob/develop/setup.py

**Comment by vital-edu** [comment]
Resolvido em radar-parlamentar/radar#400
